[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'custom-tag=node_modules/@openzeppelin/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config